#Настройки
settings:
  
  #MySQL
  db:
    
    #Хост
    host: '127.0.0.1'
    #Пользователь
    user: 'user'
    #Пароль
    pass: 'pass'
    #База
    base: 'base'
    
  #Перки
  perks:
    
    #Ловкость, шанс уворота от урона
    Dexterity: 
      name: '&bЛовкость'
      value: 0.5
    #Живучесть, увеличение максимального здоровья
    Survivabillity: 
      name: '&aЖивучесть'
      value: 2.0
    #Стальная кожа, уменьшение урона
    MetalLeather: 
      name: '&aСтальная кожа'
      value: 0.5
    #Скороход, увеличение скорости ходьбы
    Walker: 
      name: '&bСкороход'
      value: 0.05
    #Охотник, шанс увеличения лута
    Hunter: 
      name: '&eОхотник'
      value: 5
    #Кулинария, для других плагинов
    Cooking:
      name: '&eКулинария'
    #Ремесло, для других плагинов
    Craft:
      name: '&eРемесло'
    #Красноречие, для других плагинов
    Eloquence:
      name: '&eКрасноречие'
    #Медицина, для других плагинов
    Medicine:
      name: '&eМедицина'
    #Экономия энергии, уменьшение скорости понижения голода
    SaveEnergy:
      name: '&aЭкономия энергии'